# Generated by Django 5.1.1 on 2024-09-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='creado_en',
            new_name='fecha_envio',
        ),
    ]
